# Define a default target
.PHONY: default
default: install

# Install dependencies
.PHONY: install
install:
	pip install -r requirements-dev.txt

# Run the application locally
.PHONY: run
run:
	python index.py
