AWSTemplateFormatVersion: 2010-09-09
Description: Puente Data Exporter - API Gateway with Lambda Integrations
Parameters:
  version:
    Type: String
    Default: dev
  apiGatewayName:
    Type: String
    Default: my-api
  apiGatewayStageName:
    Type: String
    AllowedPattern: "[a-z0-9]+"
    Default: call
  apiGatewayHTTPMethod:
    Type: String
    Default: POST
  lambdaFunctionName:
    Type: String
    AllowedPattern: "[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+"
    Default: my-function

Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: An API Gateway with a Lambda Integration
      EndpointConfiguration:
        Types:
          - EDGE
      Name: !Sub "puente-exporter-api-${version}"
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: 'lambda'
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        ConnectionType: INTERNET
        Credentials: !GetAtt ApiGatewayIamRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: WHEN_NO_MATCH
        TimeoutInMillis: 29000
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations'
      OperationName: 'lambda'
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: !Ref ApiGatewayRestApi
      Schema: {}
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      Description: Lambda API Stage v0
      RestApiId: !Ref ApiGatewayRestApi
      StageName: !Sub "${version}"
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      Description: Lambda API Deployment
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: !Sub "LambdaAccess-${version}"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'lambda:*'
                Resource: !GetAtt LambdaFunction.Arn
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../lambdas/hello-world/hello-world.zip
      Description: AWS Lambda function
      FunctionName: !Sub "lambda-function-${version}"
      Handler: lambdas/hello-world/index.handler
      MemorySize: 256
      Role: !GetAtt LambdaIamRole.Arn
      Runtime: python3.7
      Timeout: 60
  LambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'



# LEFT FOR FUTURE USE
  # ApiGatewayAccount:
  #   Type: 'AWS::ApiGateway::Account'
  #   Properties:
  #     CloudWatchRoleArn: !GetAtt 
  #       - CloudWatchRole
  #       - Arn
  # ApiGatewayResourceSocial:
  #   Type: 'AWS::ApiGateway::Resource'
  #   Properties:
  #     ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
  #     PathPart: social
  #     RestApiId: !Ref ApiGatewayRestApi
  # ApiGatewayResourceGeneric:
  #   Type: 'AWS::ApiGateway::Resource'
  #   Properties:
  #     ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
  #     PathPart: generic
  #     RestApiId: !Ref ApiGatewayRestApi
  # ApiGatewayResourceDelete:
  #   Type: 'AWS::ApiGateway::Resource'
  #   Properties:
  #     ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
  #     PathPart: delete
  #     RestApiId: !Ref ApiGatewayRestApi
  # ApiGatewayPostMethodGeneric:
  #   DependsOn: LambdaPermissionGeneric
  #   Type: 'AWS::ApiGateway::Method'
  #   Properties:
  #     ApiKeyRequired: false
  #     AuthorizationType: NONE
  #     HttpMethod: POST
  #     Integration:
  #       ConnectionType: INTERNET
  #       # Credentials: !GetAtt ApiGatewayIamRole.Arn
  #       IntegrationHttpMethod: POST
  #       PassthroughBehavior: WHEN_NO_MATCH
  #       TimeoutInMillis: 29000
  #       Type: AWS_PROXY
  #       Uri: !Sub >-
  #         arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionGenericAssets.Arn}/invocations
  #     OperationName: generic
  #     ResourceId: !Ref ApiGatewayResourceGeneric
  #     RestApiId: !Ref ApiGatewayRestApi
  # ApiGatewayOptionsMethod:
  #   Type: AWS::ApiGateway::Method
  #   Properties:
  #     AuthorizationType: NONE
  #     RestApiId: !Ref ApiGatewayRestApi
  #     ResourceId: !Ref ApiGatewayResourceGeneric
  #     HttpMethod: OPTIONS
  #     Integration:
  #       Type: MOCK
  #       IntegrationResponses:
  #       - StatusCode: "200"
  #         ResponseParameters:
  #           method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
  #           method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
  #           method.response.header.Access-Control-Allow-Origin: "'*'"
  #         ResponseTemplates:
  #           application/json: ''
  #       PassthroughBehavior: WHEN_NO_MATCH
  #       RequestTemplates:
  #         application/json: '{"statusCode": 200}'
  #     MethodResponses:
  #     - StatusCode: "200"
  #       ResponseModels:
  #         application/json: 'Empty'
  #       ResponseParameters:
  #         method.response.header.Access-Control-Allow-Headers: false
  #         method.response.header.Access-Control-Allow-Methods: false
  #         method.response.header.Access-Control-Allow-Origin: false
  # ApiGatewayModel:
  #   Type: 'AWS::ApiGateway::Model'
  #   Properties:
  #     ContentType: application/json
  #     RestApiId: !Ref ApiGatewayRestApi
  #     Schema: {}
  # ApiGatewayStage:
  #   DependsOn:
  #       - ApiGatewayAccount
  #   Type: 'AWS::ApiGateway::Stage'
  #   Properties:
  #     DeploymentId: !Ref ApiGatewayDeployment
  #     Description:  !Sub "Lambda API Stage ${version}"
  #     RestApiId: !Ref ApiGatewayRestApi
  #     StageName: !Sub "${version}"
  #     MethodSettings:
  #       - ResourcePath: "/*"
  #         HttpMethod: "*"
  #         MetricsEnabled: true
  #         DataTraceEnabled: false
  #         LoggingLevel: INFO
  # ApiGatewayDeployment:
  #   Type: 'AWS::ApiGateway::Deployment'
  #   DependsOn: 
  #   - ApiGatewayPostMethodGeneric
  #   Properties:
  #     Description: !Sub "Zeus Prime Social Lambda API Deployment ${version}"
  #     RestApiId: !Ref ApiGatewayRestApi
  # ApiGatewayIamRole:
  #   Type: 'AWS::IAM::Role'
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: ''
  #           Effect: Allow
  #           Principal:
  #             Service:
  #               - apigateway.amazonaws.com
  #           Action:
  #             - 'sts:AssumeRole'
  #     Path: /
  #     Policies:
  #       - PolicyName: !Sub "LambdaAccess-${version}"
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action: 'lambda:*'
  #               Resource: !GetAtt LambdaFunctionGenericAssets.Arn
  #             - Effect: Allow
  #               Action: 'lambda:*'
  #               Resource: !GetAtt LambdaFunctionSocialAssets.Arn
  #             - Effect: Allow
  #               Action: 'lambda:*'
  #               Resource: !GetAtt LambdaFunctionDeleteAssets.Arn
  # LambdaPermissionGeneric:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !GetAtt LambdaFunctionGenericAssets.Arn
  #     Action: lambda:InvokeFunction
  #     Principal: 'apigateway.amazonaws.com'
  #     SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*/*"
  # LambdaFunctionGenericAssets:
  #     Type: 'AWS::Lambda::Function'
  #     Properties:
  #       Code: ../lambdas/generic-assets/generic-assets.zip
  #       Description: Lambda function for pulling generic assets and storing them in s3
  #       FunctionName: !Sub "zeus-prime-generic-asset-uploading-${version}"
  #       Handler: lambdas/generic-assets/index.handler
  #       MemorySize: 256
  #       Role: !GetAtt LambdaIamRole.Arn
  #       Runtime: nodejs14.x
  #       Timeout: 60
  #     Metadata:
  #       cfn-lint:
  #         config:
  #           ignore_checks:
  #           - W3002
  # LambdaIamRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - lambda.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
  #     Policies:
  #       - PolicyName: !Sub "S3Access-${version}"
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action: 's3:*'
  #               Resource: "*"
  #             - Effect: Allow
  #               Action: 'kms:*'
  #               Resource: "*"
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  # LogGroupLambdaFunctionGenericAssets:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Join ['/', ['/aws/lambda',!Ref LambdaFunctionGenericAssets]]
  #     RetentionInDays: 7 # days
  # CloudWatchRole:
  #   Type: 'AWS::IAM::Role'
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - apigateway.amazonaws.com
  #           Action: 'sts:AssumeRole'
  #     Path: /
  #     ManagedPolicyArns:
  #       - >-
  #         arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs