class Outputs:
    JSON = 'json'
    PICKLE_DICT = 'pickle_dict'
    PICKLE_DATAFRAME = 'pickle_df'
    PICKLE_LIST = 'pickle_list'


class PuenteTables:
    ROLE = 'Role'
    SESSION = 'Session'
    USER = 'User'
    ALLERGIES = 'Allergies'
    ASSETS = 'Assets'
    # B4A_CUSTOM_FIELD = 'B4aCustomField'
    # B4A_MENU_ITEM = 'B4aMenuItem'
    # B4A_SETTING = 'B4aSetting'
    EVALUATION_MEDICAL = 'EvaluationMedical'
    FORM_ASSET_RESULTS = 'FormAssetResults'
    FORM_RESULTS = 'FormResults'
    FORM_SPECIFICATIONS = 'FormSpecificationsV2'
    HISTORY_ENVIRONMENTAL_HEALTH = 'HistoryEnvironmentalHealth'
    HISTORY_MEDICAL = 'HistoryMedical'
    HOUSEHOLD = 'Household'
    SURVEY_DATA = 'SurveyData'
    VITALS = 'Vitals'
    OFFLINE_FORM = 'offlineForm'
    OFFLINE_FORM_REQUEST = 'offlineFormRequest'
